version: '3.1'

services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: rails7_development
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp/
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mysql_data: